{
 "title": "get_customers_v1_seconds_count",
 "time": { "from": "2019-05-11T14:41:00.137Z", "to": "2019-05-11T14:44:13.351Z" },
 "panels": [
  {
   "title": "get_customers_v1_seconds_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "get_customers_v1_seconds_count" }
   ]
  },
  {
   "title": "get_customers_v1_seconds_count{status=\"500\"}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "get_customers_v1_seconds_count{status=\"500\"}"
    }
   ]
  },
  {
   "title": "increase(get_customers_v1_seconds_count{status=\"200\"}[$__range])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(get_customers_v1_seconds_count{status=\"200\"}[$__range])"
    }
   ]
  },
  {
   "title": "rate(get_customers_v1_seconds_count{status=\"200\"}[$__range])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(get_customers_v1_seconds_count{status=\"200\"}[$__range])"
    }
   ]
  },
  {
   "title": "get_customers_v1_seconds_count{status=\"200\"}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "get_customers_v1_seconds_count{status=\"200\"}"
    }
   ]
  }
 ]
}