{
 "title": "Exercise 3",
 "time": { "from": "2019-05-12T17:41:05.479Z", "to": "2019-05-12T17:45:19.001Z" },
 "panels": [
  {
   "title": "Total Orders placed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(post_orders_v1_seconds_count{status=\"201\"}[$__range])"
    }
   ]
  },
  {
   "title": "Payment mix",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(createOrderPaymentMethod_creditcardv1_total[1m])",
     "legendFormat": "CC"
    },
    {
     "expr": "increase(createOrderPaymentMethod_idealv1_total[1m])",
     "legendFormat": "Ideal"
    },
    {
     "expr": "increase(createOrderPaymentMethod_postpaidv1_total[1m])",
     "legendFormat": "PostPaid"
    }
   ]
  },
  {
   "title": "CreditCard",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(createOrderPaymentMethod_creditcardv1_total[$__range])"
    }
   ]
  },
  {
   "title": "iDeal",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(createOrderPaymentMethod_idealv1_total[$__range])"
    }
   ]
  },
  {
   "title": "PostPaid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(createOrderPaymentMethod_postpaidv1_total[$__range])"
    }
   ]
  }
 ]
}