{
 "title": "Exercise 2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total requests (since forever)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "get_customers_v1_seconds_count{exception=\"None\"}"
    }
   ]
  },
  {
   "title": "Total requests in selected time range",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(get_customers_v1_seconds_count{exception=\"None\"}[$__range])"
    }
   ]
  },
  {
   "title": "Min/Max/Avg response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "min(get_customers_v1_seconds)" },
    { "expr": "max(get_customers_v1_seconds)" },
    { "expr": "avg(get_customers_v1_seconds)" }
   ]
  },
  {
   "title": "Failed requests (ApplicationException)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(get_customers_v1_seconds_count{exception=\"ApplicationException\"}[$__range])"
    }
   ]
  },
  {
   "title": "Success vs. Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(get_customers_v1_seconds_count{status=\"200\"}[$__range])",
     "legendFormat": "200"
    },
    {
     "expr": "increase(get_customers_v1_seconds_count{status!=\"200\"}[$__range])",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}