{
 "title": "GET /customers",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total requests (since forever)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "get_customers_v1_seconds_count{exception=\"None\"}"
    }
   ]
  },
  {
   "title": "Total requests ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(get_customers_v1_seconds_count{exception=\"None\"}[$__range])"
    }
   ]
  },
  {
   "title": "Min/Max/Avg response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "min(get_customers_v1_seconds)" },
    { "expr": "max(get_customers_v1_seconds)" },
    { "expr": "avg(get_customers_v1_seconds)" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(get_customers_v1_seconds_count[$__range])"
    }
   ]
  },
  {
   "title": "Failed requests (ApplicationException)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(get_customers_v1_seconds_count{exception=\"ApplicationException\"}[$__range])"
    }
   ]
  }
 ]
}